sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          input_type: text
          antlers: false
          display: Name
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: description
        field:
          input_type: text
          antlers: false
          display: Description
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          width: 50
      -
        handle: author
        field:
          input_type: text
          antlers: false
          display: Author
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          width: 50
      -
        handle: donate
        field:
          collapse: accordion
          sets:
            sponsor:
              display: Sponsor
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: icon
                  field:
                    input_type: text
                    antlers: false
                    display: Icon
                    type: text
                    icon: text
                    listable: hidden
                    instructions_position: above
                -
                  handle: link
                  field:
                    display: Link
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
          display: Donate
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
      -
        handle: analytics
        field:
          antlers: false
          display: Analytics
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
