title: Produce
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: color
        field:
          type: terms
          taxonomies:
            - color
          display: Color
          mode: select
          width: 33
      -
        handle: stats_plus
        field:
          inline: false
          options:
            pwr: Pwr
            skl: Skl
            def: Def
            mgc: Mgc
            hp: HP
            spr: Spr
            chm: Chm
            lck: Lck
            agg: Agg
            frd: Frd
            clm: Clm
            arr: Arr
            ind: Ind
            sch: Sch
            laz: Laz
            lon: Lon
          display: 'Stats +'
          type: checkboxes
          icon: checkboxes
          width: 33
          listable: hidden
          instructions_position: above
      -
        handle: stats_minus
        field:
          inline: false
          options:
            pwr: Pwr
            skl: Skl
            def: Def
            mgc: Mgc
            hp: HP
            spr: Spr
            chm: Chm
            lck: Lck
            agg: Agg
            frd: Frd
            clm: Clm
            arr: Arr
            ind: Ind
            sch: Sch
            laz: Laz
            lon: Lon
          display: 'Stats -'
          type: checkboxes
          icon: checkboxes
          width: 33
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - produce
          max_items: 1
          listable: false
          localizable: true
