title: Meta
fields:
  -
    handle: meta_title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      instructions: 'override the default page title'
      listable: hidden
      instructions_position: above
  -
    handle: meta_description
    field:
      input_type: text
      antlers: false
      display: Description
      type: text
      icon: text
      instructions: 'override the site description'
      listable: hidden
      instructions_position: above
