title: Produce
template: produce/show
layout: layout
taxonomies:
  - color
revisions: false
route: '/encyclopedias/produce/{parent_uri}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
